version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: underbelle_user
      POSTGRES_PASSWORD: underbelle_pass
      POSTGRES_DB: underbelle_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
